server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  web:
    encoding:
      charset: UTF-8
      force: true
  application:
    name: db-service
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/db_service
    username: boomzin
    password: boomzin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 20
      minimumIdle: 1
      idleTimeout: 60000
  jooq:
   sql-dialect: POSTGRES
logging:
  level:
    org.springframework.boot.autoconfigure.jooq: DEBUG
    org.jooq: DEBUG